name: Release

on:
  release:
    types:
      - prereleased
      - released

jobs:

  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: installing cargo-edit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-edit

      - name: setting release version
        uses: actions-rs/cargo@v1
        with:
          command: set-version
          args: ${{github.ref_name}}

      - name: publishing lib
        run: cargo publish --token ${CRATESIO_TOKEN} -p dcl-crypto --allow-dirty
        env:
          CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
